# Standard Statistics Redressed

This is the section that most of you will find more familiar as we cover concepts typically considered "classical" statistics. These methods are tried and true, and are perhaps the most frequently seen in the literature and scientific presentations. In the best case, your data will match one of the these methods exactly. Many research projects are specifically designed to fit one of these classical techniques. Often, we may be able to transform our data or modify our model to fit a classical technique. However, this comes with the caveat that it will change the interpretability of our fitted model, and may make it more difficult to report or compare the results. But, this trade off comes with a number of positive attributes including 
- Increasing the ability to improve the computational speed and stability of our analysis
- Stable definitions of parameter estimation
- Efficient communication of analytical methods
- utilize existing R machinery

However, I strongly believe that our efforts taken build our own deterministic and statistical models engrained a deeper understanding of math and probability. These efforts should 


## General Linear Models

## Example one

## Example two
